### ISSUE TITLE
IDBObjectStoreParameters prim__new syntax error

### ISSUE THREAD

**Issue by MarcelineVQ** [stefan-hoeck/idris2-dom#21]
Currently when my browser loads a js source that used [`IDBObjectStoreParameters.prim__new`](https://github.com/stefan-hoeck/idris2-dom/blob/main/src/Web/Internal/IndexedDBPrim.idr#L597) I get an error in the console of
`Uncaught SyntaxError: Unexpected token ':'`

The code for prim__new is
`%foreign "browser:lambda:(a,b)=> {keyPath: a,autoIncrement: b}"`

Seems that it should be
`%foreign "browser:lambda:(a,b)=> ({keyPath: a,autoIncrement: b})"`
With regards to this SO post https://stackoverflow.com/a/28770578
In order to prevent JS from treating the { } as a block statement.

There are other places in the codebase this issue could potentionally occur, e.g.
https://github.com/stefan-hoeck/idris2-dom/blob/main/src/Web/Internal/IndexedDBPrim.idr#L570
https://github.com/stefan-hoeck/idris2-dom/blob/main/src/Web/Internal/AnimationPrim.idr#L622

**Comment by stefan-hoeck** [comment]
Thanks for reporting this. This was a bug in the idris2-webidl codegen. It was fixed in #20.
